version: "3.8"

services:
  backend:
    build:
      context: ./backend/
    environment:
      $FORWARDED_ALLOW_IPS: "*"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./
    ports:
      - "4200:4200"
    depends_on:
      - backend